/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.71
 * Generated at: 2021-11-28 08:33:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Test.webapp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import notice.Notice;
import notice.noticeDAO;
import java.util.ArrayList;

public final class avengersInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("notice.Notice");
    _jspx_imports_classes.add("notice.noticeDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("    #movieInfo{\r\n");
      out.write("        display:grid;\r\n");
      out.write("        grid-template-columns: 300px 700px;\r\n");
      out.write("        grid-template-rows: 300px 150px;\r\n");
      out.write("\r\n");
      out.write("        grid-template-areas: \r\n");
      out.write("        \"movieThumb movieContent\"\r\n");
      out.write("        \"movieStory movieStory\";\r\n");
      out.write("    }\r\n");
      out.write("    #movieThumb { grid-area :movieThumb;}\r\n");
      out.write("    #movieContent{grid-area : movieContent}\r\n");
      out.write("    #movieStory{grid-area : movieStory}\r\n");
      out.write("    #curCommentBox{\r\n");
      out.write("        display:grid;\r\n");
      out.write("        grid-template-columns: 100px 800px 100px;\r\n");
      out.write("        grid-template-rows: 100px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");

String movieTitle = "avengersEndgame";
session.setAttribute("movieTitle",movieTitle);
String userID = null;
if(session.getAttribute( "userID") != null){
userID = (String) session.getAttribute("userID");
}

int pageNumber =1 ;
if(request.getParameter("pageNumber")!=null){
	pageNumber = Integer.parseInt(request.getParameter("pageNumber"));
}

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <div id = \"header\" style=\"z-index: 2;\">\r\n");
      out.write("            <div id = \"title\">\r\n");
      out.write("                <h1>MOVIE STAR</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("                <div id =\"nav\">\r\n");
      out.write("                    <ul style=\"list-style-type: none; overflow: hidden;\">\r\n");
      out.write("                        <li class=\"active\"><a href=\"#\">HOME</a></li>\r\n");
      out.write("                        <li><a href=\"#\">MOVIE</a></li>\r\n");
      out.write("                        <li><a href=\"#\">게시판</a></li>\r\n");
      out.write("                        \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div id=\"login-form\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                    ");

				if(userID == null){
					
      out.write("\r\n");
      out.write("                    <a href=\"login.html\">Sign In</a>\r\n");
      out.write("                    <a href=\"signUp.html\">Sign Up</a>\r\n");
      out.write("                    ");
}
                    else{
                    
      out.write("\r\n");
      out.write("                    Welcome ");
      out.print(userID );
      out.write("\r\n");
      out.write("                    <a href=\"logoutAction.jsp\">Log Out</a>\r\n");
      out.write("                    ");
}
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("        </div> \r\n");
      out.write("	<div id=\"movieInfo\" style=\"width:1000px; border:1px solid black; padding:10px; margin:10px; display: grid;\">\r\n");
      out.write("        <div id=\"movieThumb\" style=\"float:left;\">\r\n");
      out.write("            <img src=\"avengers.jpg\" style=\"width:200px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id = \"movieContent\" style=\"\">\r\n");
      out.write("            어벤저스 : 엔드게임<br><br>\r\n");
      out.write("            감독 : 앤서니 루소, 조 루소 <br><br>\r\n");
      out.write("            배우 : 로버트 다우니 주니어, ...\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id = \"movieStory\" >\r\n");
      out.write("            타노스를 막아라 어벤저스용사들!!타노스를 막아라 어벤저스용사들!!타노스를 막아라 어벤저스용사들!!타노스를 막아라 어벤저스용사들!!타노스를 막아라 어벤저스용사들!!\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <form method=\"POST\" action=\"writeAction.jsp\" id=\"myForm\">\r\n");
      out.write("    <div id = \"commentBox\" style=\"width:1000px; border:1px solid black; padding:10px; margin:10px;\">\r\n");
      out.write("        <div id=\"comment\">\r\n");
      out.write("            <textarea rows=\"5\" style=\"width:1000px; font-size:15px;\"name=\"noticeContent\"></textarea>\r\n");
      out.write("        </div>\r\n");
      out.write("        별점\r\n");
      out.write("        <select name=\"movieStar\" form=\"myForm\">\r\n");
      out.write("            <option value=\"5\">5</option>\r\n");
      out.write("            <option value=\"4\">4</option>\r\n");
      out.write("            <option value=\"3\">3</option>\r\n");
      out.write("            <option value=\"2\">2</option>\r\n");
      out.write("            <option value=\"1\">1</option>\r\n");
      out.write("        </select>\r\n");
      out.write("        <input type=\"submit\" value=\"댓글작성\">\r\n");
      out.write("    </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    <div id=\"curCommentBox\"  style=\"width:1000px; border:1px solid black; padding:10px; margin:10px;\">\r\n");
      out.write("        <div id=\"userid\" style=\"border:1px solid black;\">userID</div>\r\n");
      out.write("        <div id=\"curComment\"style=\"border:1px solid black;\">정말 훌륭하고 재미있는 영화입니다 짱짱맨</div>\r\n");
      out.write("        <div id=\"star\"style=\"border:1px solid black;\">5.0</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

    noticeDAO noticeDAO = new noticeDAO(); 
        ArrayList<Notice> list = noticeDAO.getList(pageNumber);
    	for(int i = 0; i< list.size(); i++){
    
      out.write("\r\n");
      out.write("    <div id=\"curCommentBox\"  style=\"width:1000px; border:1px solid black; padding:10px; margin:10px;\">\r\n");
      out.write("        <div id=\"userid\" style=\"border:1px solid black;\">");
      out.print( list.get(i).getUserId() );
      out.write("</div>\r\n");
      out.write("        <div id=\"curComment\"style=\"border:1px solid black;\">");
      out.print( list.get(i).getNoticeContent() );
      out.write("</div>\r\n");
      out.write("        <div id=\"star\"style=\"border:1px solid black;\">");
      out.print( list.get(i).getMovieStar() );
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
